/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.joeltobey.spring.boot.starter.client;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
